### ISSUE TITLE
Tests shouldn't depends on a global lib, `mocha` should be part of the `devDependencies`.

### ISSUE THREAD

**Issue by lutangar** [Datagora-erasme/datagora_datatlas_back#3]
Tests shouldn't depends on a global lib, `mocha` should be part of the `devDependencies`.

_Originally posted by @lutangar in https://github.com/datatlas-erasme/back/pull/2#discussion_r941421278_

**Comment by racine-p-a** [comment]
@lutangar 
Should be done. Am I missing something on this issue ?
https://github.com/datatlas-erasme/back/commit/0499e4eb62666bcf0334a795e7a0aaf33acc3038

**Comment by Pipazoul** [comment]
Updated the readme https://github.com/datatlas-erasme/back/pull/7

**Comment by Pipazoul** [comment]
@lutangar  @racine-p-a  can we close this issue ?

**Comment by lutangar** [comment]
This is still an issue, last commits aaf70efb6d5353ec3594222636cec4041b8b9bdc and 403841f15b6dd42ff35ef5f17a7a9b74419f23a7 aren't on `dev` branch.

Here's my suggestion for the "testing" part of the doc :
https://pad.georgette.party/wTiB8H8PSaydeI0vWQ391A?both

Feel free to disagree and adapt !
